- alias: 'ALARM - Armed_Away'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
  action:
    - service: media_player.media_stop
      data_template:
        entity_id: media_player.living_room_speaker 
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room_speaker
        volume_level: 0.2      
    - service: media_player.play_media
      data_template:
        entity_id: media_player.living_room_speaker
        media_content_id: !secret alarm_beep
        media_content_type: music 
