- alias: 'ALARM - Pending'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'pending' 
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.living_room_speaker
        volume_level: 0.2      
    - service: media_player.play_media
      data_template:
        entity_id: media_player.living_room_speaker
        media_content_id: !secret alarm_pending
        media_content_type: music
