- alias: "CHELSEA - Home Boolean"
  trigger:
  - entity_id: person.chelsea
    platform: state
    from: 'not_home' 
    to: 'home' 
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.chelsea_home
  
- alias: "CHELSEA - Away Boolean"  
  trigger:
  - entity_id: person.chelsea
    platform: state
    from: 'home' 
    to: 'not_home' 
    for:
      minutes: 10
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.chelsea_home