homeassistant:
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
        
default_config:
discovery:
  ignore:
    - igd
    
climate:
  - platform: generic_thermostat
    name: Pool Temperature
    heater: switch.hac1_channel_2
    target_sensor: sensor.converted_pool_temp
    min_temp: 32
    max_temp: 95
    initial_hvac_mode: "off"

device_tracker:
  - platform: linksys_smart
    host: 192.168.1.1
    interval_seconds: 10
    consider_home: 00:10:00
    
frontend:
  themes: !include themes.yaml
  javascript_version: latest
  
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

light: !include lights.yaml 
sensor: !include sensors.yaml
switch: !include switches.yaml
input_boolean: !include input_boolean.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations/
script: !include scripts.yaml
zone: !include zones.yaml
camera: !include cameras.yaml
history: !include history.yaml
binary_sensor: !include binary_sensor.yaml
stream:
recorder:

weather:
  - platform: darksky
    mode: daily
    api_key: !secret darksky_key
    
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_key

tuya:
  username: !secret tuya_user
  password: !secret tuya_pass
  country_code: 1
  platform: smart_life
  
sonoff:
  username: !secret sonoff_user
  password: !secret sonoff_pass
  api_region: 'us'
  
ifttt:
  key: !secret ifttt_key
    
remote:
  - platform: harmony
    name: Livingroom Hub
    host: 192.168.1.228
  - platform: harmony
    name: Bedroom Hub
    host: 192.168.1.241
  - platform: harmony
    name: Basement Hub
    host: 192.168.1.229

media_player:
  - platform: emby
    host: 192.168.1.240
    api_key: !secret emby_key

tts:
  - platform: google_translate
    service_name: google_say

emulated_hue:
  host_ip: !secret hassio_ip
  listen_port: 80
  expose_by_default: false
  entities:
    light.dummy_light:
      name: "Dummy Light"
      hidden: false
      
google_assistant:
  project_id: !secret google_id
  service_account: !include My Project-1cf41535cd7b.json
  expose_by_default: false
  entity_config:
    script.google_pool_temp:
      expose: true
      name: Pool Temperature
    script.google_internet_speed:
      expose: true
      name: Internet Speed
    
speedtestdotnet:
  scan_interval:
    days: 0
    hours: 0
    minutes: 30
    seconds: 0
    milliseconds: 0
    
notify:
  - name: lucy_doorbell
    platform: smtp
    server: smtp-mail.outlook.com
    port: 587
    sender: !secret lucy_email
    username: !secret lucy_email
    password: !secret lucy_password
    recipient:
      - !secret email_recip1
      - !secret email_recip2
    sender_name: Lucy
  - platform: alexa_media
    name: alexa_media
  
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    pending_time: 0
    delay_time: 0
    trigger_time: 600
    disarmed:
      trigger_time: 0
    armed_away:
      pending_time: 30
      delay_time: 20
    armed_home:
      pending_time: 0
      delay_time: 0
      
timer:
  5_seconds:
    duration: '00:00:05'   
    
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret    
