- alias: 'MOTION - Bedroom during day'
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_motion
      to: 'on'
  condition:
  - condition: time
    after: '10:00:00'
    before: '19:59:59'
  - condition: state
    entity_id: light.bedroom
    state: 'off'
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: "Bedroom"
        scene_name: "Bright" 
    - service: notify.alexa_media
      data_template:
        target:
          - media_player.bedroom
        data:
          type: tts
        message: Hello there
    - delay: '00:00:15'    