- alias: "POOL - Pump Timer-ON from HA"
  trigger:
  - entity_id: switch.pool_pump_timer
    platform: state
    to: 'on'
  action:
    - service: switch.turn_on
      entity_id:
      - switch.hac1_software_switch_3 

- alias: "POOL - Pump Timer-OFF from HA"
  trigger:
  - entity_id: switch.pool_pump_timer
    platform: state
    to: 'off'
  action:
    - service: switch.turn_off
      entity_id:
      - switch.hac1_software_switch_3