- alias: "POOL Thermostat-ON (From Switch)"
  trigger:
  - platform: state
    entity_id: switch.hac1_software_switch_1
    to: 'on'
  action:
    - service: climate.turn_on
      entity_id: climate.pool_temperature
      
- alias: "POOL - Thermostat-OFF (From Switch)"
  trigger:
  - platform: state
    entity_id: switch.hac1_software_switch_1
    to: 'off'
  action:
    - service: climate.turn_off
      entity_id: climate.pool_temperature
